FinanceAPP/Controllers/FinanceItemsController.cs
using FinanceService.Services;
using FinanceService.Services.UploadFile;
using FinanceService.Contracts.UploadFile;
using System.IO;
using FinanceService.Contracts.TransferExcel2List;
using FinanceShared;
using FinanceService.Contracts.Partner;
using FinanceService.Contracts.FinancialItam;
using FinanceService.Services.Partner;
using Serilog;
using Microsoft.VisualBasic;

using System.Web.Mvc;
using System.Linq;
using System;
using System.Web;
using System.Globalization;
using FinanceService.Contracts.PartnerFinancialItem;
using System.Collections.Generic;

namespace FinanceAPP.Controllers
{
    public class FinanceItemsController : Controller
    {
        //private IWebHostEnvironment _webHostEnvironment;
        private IUploadFile _uploadFileSrv;
        private ITransferExcel2List<FinancialItemsDTO> _transferExcel2ListSrv;
        private IPartner _partnerSrv;
        private IFinancialItem _financialItemSrv;
        private IPartnerFinancialItems _partnerFinancialItemsSrv;
        //public FinanceItemsController(IWebHostEnvironment webHostEnvironment, IUploadFile uploadFileSrv, ITransferExcel2List<FinancialItemsDTO> transferExcel2ListSrv, IPartner partnerSrv, IFinancialItem financialItemSrv)
        public FinanceItemsController(IUploadFile uploadFileSrv, IPartner partnerSrv, IFinancialItem financialItemSrv, ITransferExcel2List<FinancialItemsDTO> transferExcel2ListSrv, IPartnerFinancialItems partnerFinancialItemsSrv)
        {
            //, IPartnerFinancialItems partnerFinancialItemsSrv
            //_webHostEnvironment = webHostEnvironment;
            _uploadFileSrv = uploadFileSrv;
            _transferExcel2ListSrv = transferExcel2ListSrv;
            _partnerSrv = partnerSrv;
            _financialItemSrv = financialItemSrv;
            _partnerFinancialItemsSrv = partnerFinancialItemsSrv;
        }

        public ActionResult Index()
        {
            TempData["header"] = "Upload Finance Items";

            return View();
        }
        /// <summary>
        /// Upload Finance Items
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(HttpPostedFileBase file)
        {
           
            try
            {
                if(file == null) {
                    TempData["header"] = "Upload Finance Items";
                    return View(); 
                }

                string uploadFolder = Server.MapPath("~/Temp/FinanceItemFiles");
                String message = "";
                int numberRecords = 0;

                string fileName = _uploadFileSrv.UploadFile(uploadFolder, file);
                List<FinancialItemsDTO> financialItems = _transferExcel2ListSrv.TransferExcel2List(Path.Combine(uploadFolder, fileName));
                numberRecords = financialItems.Count;
                message = "Number records : " + numberRecords.ToString();

                financialItems = _partnerFinancialItemsSrv.RemoveFinancialItemHasWrongPatnerId(financialItems);

                message += " Number of correct information : " + financialItems.Count.ToString();
                message += " Number of wrong information : " + (numberRecords - financialItems.Count).ToString();

                Log.Information(message);

                foreach(FinancialItemsDTO financialItem in financialItems)
                {
                    financialItem.FinancialId = Guid.NewGuid();
                }

                GlobalVariables.FINANCIAL_ITEMS_LIST.AddRange(financialItems);

                TempData["success"] = message;
            }
            catch (Exception ex)
            {
                Log.Error($" Upload Financial item {ex.ToString()}");
            }
            return View("FinancialItem", GlobalVariables.FINANCIAL_ITEMS_LIST);
        }
        /// <summary>
        /// List Of Financial Item
        /// </summary>
        /// <param name="financialItems"></param>
        /// <returns></returns>
        public ActionResult FinancialItem()
        {
            TempData["header"] = "Financial Items";

            return View(_financialItemSrv.GetAll());
        }
        /// <summary>
        /// Create Financial Item
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            try
            {
                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();
                TempData["header"] = " Create Financial Item";
            }
            catch (Exception ex)
            {
                Log.Error($" Financial item Create {ex.ToString()}");
            }
            return View();
        }

        /// <summary>
        ///  Create Financial Item
        /// </summary>
        /// <param name="financialItems"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FinancialItemsDTO financialItems)
        {
            try
            {
                TempData["header"] = "Create Financial Item";

                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();

                if (ModelState.IsValid)
                {
                    _financialItemSrv.Insert(financialItems);
                    TempData["success"] = "A new financial item has been added";
                    Log.Information($"Add new financial item {financialItems.FinancialId} by ");
                    ModelState.SetModelValue("Amount", new ValueProviderResult(string.Empty, string.Empty, CultureInfo.InvariantCulture));

                }
            }
            catch (Exception ex)
            {
                Log.Error($" Create Financial item {ex.ToString()}");
            }

            return View(financialItems);
        }

        /// <summary>
        /// Edit Financial Item
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit(Guid financialId)
        {
            FinancialItemsDTO financialItem = new FinancialItemsDTO();
            try
            {
                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();

                financialItem = _financialItemSrv.Get(financialId);

                TempData["header"] = "Edit Financial Item";
            }
            catch (Exception ex)
            {
                Log.Error($" Edit Financial item {ex.ToString()}");
            }
            return View(financialItem);
        }

        /// <summary>
        ///  Edit Financial Item
        /// </summary>
        /// <param name="financialItems"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FinancialItemsDTO financialItems)
        {

            TempData["header"] = "Edit Financial Item";
            try
            {
                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();

                if (ModelState.IsValid)
                {
                    if (_financialItemSrv.Update(financialItems))
                    {
                        Log.Information($"Update financial item {financialItems.FinancialId} by ");
                        TempData["success"] = " Financial item updated successfully";
                    }
                    else
                    {
                        Log.Warning($"Could not find financial item {financialItems.FinancialId} by ");
                        TempData["success"] = "We Could not Update Financial Item";
                    }
                    return RedirectToAction("FinancialItem");
                }

            }
            catch (Exception ex)
            {
                Log.Error($" Edit Financial item {ex.ToString()}");
            }
            return View(financialItems);
        }

        /// <summary>
        /// Delete Financial Item
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete(Guid financialId)
        {
            FinancialItemsDTO financialItem = new FinancialItemsDTO();
            try
            {
                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();

                financialItem = _financialItemSrv.Get(financialId);

                TempData["header"] = "Delete Financial Item";
            }
            catch (Exception ex)
            {
                Log.Error($" Delete Financial item {ex.ToString()}");
            }
            return View(financialItem);
        }

        /// <summary>
        ///  Delete Financial Item
        /// </summary>
        /// <param name="financialItems"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FinancialItemsDTO financialItems)
        {
            try
            {
                TempData["header"] = "Edit Financial Item";

                ViewBag.PartnerList = _partnerSrv.GetAllPartner().Select(o => new SelectListItem { Value = o.Partner_Id.ToString(), Text = o.Partner_Id.ToString() }).ToList();

                if (_financialItemSrv.Delete(financialItems.FinancialId))
                {
                    Log.Information($"Delete financial item {financialItems.FinancialId} by ");
                    TempData["success"] = "Financial Item deleted successfully";
                }
                else
                {

FinanceAPP/Controllers/PartnersController.cs
using FinanceService.Contracts.Partner;
using FinanceService.Contracts.TransferExcel2List;
using FinanceService.Contracts.UploadFile;
using FinanceService.Services.TransferExcel2List;
using FinanceService.Services.UploadFile;
using FinanceShared;
using Serilog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceAPP.Controllers
{
    public class PartnersController : Controller
    {
        private IPartner _partnerSrv;
        private IUploadFile _uploadFileSrv;
        private ITransferExcel2List<PartnersDTO> _transferExcel2ListSrv;

        public PartnersController(IPartner partnerSrv, IUploadFile uploadFileSrv, ITransferExcel2List<PartnersDTO> transferExcel2ListSrv)
        {
            _partnerSrv = partnerSrv;
            _uploadFileSrv = uploadFileSrv;
            _transferExcel2ListSrv = transferExcel2ListSrv;
        }
        // GET: Partners
        /// <summary>
        /// Generate Partner
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                TempData["header"] = "Generate Partner";
                if (_partnerSrv.GetAllPartner().Count == 0)
                {
                    _partnerSrv.CreatePartner(10, 40, 3, 1, 20);
                    Log.Information($"Create {_partnerSrv.GetAllPartner().Count} Partner ");
                }
                return View(_partnerSrv.GetAllPartner().Select(o => new PartnersDTO
                {
                    Fee_Percent = o.Fee_Percent,
                    Partner_Id = o.Partner_Id,
                    Partner_Name = o.Partner_Name,
                    Parent_Partner_Id = o.Parent_Partner_Id,
                    Order = (o.Parent_Partner_Id == 0 ? o.Partner_Id : o.Parent_Partner_Id)
                }).OrderBy(o => o.Order).ToList());
            }
            catch (Exception ex)
            {
                Log.Error($" Details Financial item {ex.ToString()}");
            }

            return View(new PartnersDTO());
        }
        /// <summary>
        ///  Upload 
        /// </summary>
        /// <returns></returns>
        public ActionResult Upload()
        {
            return View();
        }
        /// <summary>
        /// Upload Partner
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file != null)
            {
                string uploadFolder = Server.MapPath("~/Temp/Partners");
                String message = "";
                int numberRecords = 0;
                List<PartnersDTO> partnersItems;
                try
                {
                    string fileName = _uploadFileSrv.UploadFile(uploadFolder, file);
                    partnersItems = _transferExcel2ListSrv.TransferExcel2List(Path.Combine(uploadFolder, fileName));
                    numberRecords = partnersItems.Count;
                    message = "Number records : " + numberRecords.ToString();

                    Log.Information(message);

                    for (int i = 0; i < numberRecords; i++)
                    {
                        partnersItems[i].Order = partnersItems[i].Parent_Partner_Id == 0 ? partnersItems[i].Partner_Id : partnersItems[i].Parent_Partner_Id;
                    }

                    GlobalVariables.PARTNER_LIST = partnersItems;

                    TempData["success"] = message;

                    return View(partnersItems);
                }
                catch (Exception ex)
                {
                    Log.Error($" Upload Financial item {ex.ToString()}");
                }
            }
            return View(new PartnersDTO());
        }
    }
}

FinanceAPP/Controllers/ReportController.cs
using FinanceService.Contracts.PartnerFinancialItem;
using FinanceService.Services.PartnerFinancialItems;
using FinanceShared;
using System.Collections.Generic;
using System.Web.Mvc;


namespace FinanceAPP.Controllers
{
    public class ReportController : Controller
    {
        private IPartnerFinancialItems _partnerFinancialItemsSrv;

        public ReportController(IPartnerFinancialItems partnerFinancialItemsSrv)
        {
            _partnerFinancialItemsSrv = partnerFinancialItemsSrv;

        }
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Total Amounts Member
        /// </summary>
        /// <returns></returns>
        public ActionResult TotalMembers()
        {

            TempData["header"] = "Total Members";
            //List<PartnerFinancialItemDTO> partnerFinancial = _partnerFinancialItemsSrv.SumMemberTeam();
            var partnerFinancial = _partnerFinancialItemsSrv.CalculateMembers();
            return View(partnerFinancial);
        }
        /// <summary>
        /// Total Benfit of members
        /// </summary>
        /// <returns></returns>
        public ActionResult BenfitMembers()
        {

            TempData["header"] = "Total Benfit Members";
            List<PartnerFinancialItemDTO> partnerFinancial = _partnerFinancialItemsSrv.TotalBenfitMemberTeam();
            return View(partnerFinancial);
        }
        /// <summary>
        /// TotalParentMemberTeam
        /// </summary>
        /// <returns></returns>
        public ActionResult TotalParentMemberTeam()
        {
            TempData["header"] = "Total Members";
            List<PartnerFinancialItemDTO> partnerFinancial = _partnerFinancialItemsSrv.SumParentMemberTeam();
            return View(partnerFinancial);

        }

    }
}

FinanceAPP/Views/Shared/_Header.cshtml
<h2>@TempData["header"]</h2>
<hr />
@if (TempData["success"] != null)
{
    <h4 class="alert alert-success">@TempData["success"]</h4>
}
@if (TempData["error"] != null) { 
    <h4 class="alert alert-danger">@TempData["error"]</h4>
}

FinanceAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Finance Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Url.Content("//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css")" rel="stylesheet" type="text/css" />
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js" integrity="sha512-BkpSL20WETFylMrcirBahHfSnY++H2O1W+UnEEO4yNIl+jI2+zowyoGJpbtk6bx97fBXf++WJHSSK2MV4ghPcg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.flash.min.js"></script>
    <script src="~/Scripts/DataTables/jszip.min.js"></script>
    <script src="~/Scripts/DataTables/pdfmake.min.js"></script>
    <script src="~/Scripts/DataTables/vfs_fonts.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.print.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.fixedHeader.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.responsive.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Finance</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Partner
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Generate", "Index", "Partners", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Upload", "Upload", "Partners", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Finance Item
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Manually", "FinancialItem", "FinanceItems", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Upload", "Index", "FinanceItems", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Reports
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Sum Memebr", "TotalMembers", "Report", new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Sum Memebrs & Parent", "TotalParentMemberTeam", "Report", new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Total Benfits of Memebrs", "BenfitMembers", "Report", new { area = "" }, new { @class = "nav-link" })
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>


    <div class="container body-content border border-secondary rounded p-3">


        @Html.Partial("_Header")

        @RenderBody()

    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


    @Html.Partial("_Notification")

    @RenderSection("scripts", required: false)

</body>
</html>

FinanceAPP/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}